# Generated by Django 5.1b1 on 2024-07-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_contact_sno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
