# Generated by Django 5.1b1 on 2024-07-17 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
